import json
from pathlib import Path
p=Path('docs/pdf-remediation-batch-3')
rows=json.loads((p/'triage-all.json').read_text())['entries']
selected=['core-difficulty-scale','core-round-duration','core-starvation','core-infection','core-scroll-restrictions','core-purchase-20-arrows','core-purchase-10-bolts','core-service-night-in-hospice','core-service-drink','core-service-steady-meal','core-service-bribe-guard','core-service-bribe-clerk','core-service-bribe-rabble','core-service-armor-repair-tier-1-to-2','core-service-armor-repair-tier-2-to-3','core-starting-item-bomb','core-starting-item-life-elixir','core-starting-item-small-vicious-dog','core-starting-item-monkeys']
assert all(any(r['needId']==i for r in rows) for i in selected)
selection={'baselineHead':'11e86737cce0dac67c269537e07fedb84d189e97','selectedAuditIds':selected,'uniqueSelectedPlayNeeds':10,'boundedDependencies':['Core fleeing authority and its combat/morale transitions (no invented DR)','Negative HP and critical search routing within the combat loop','Character carrying/casting contextual access','Restore daily Power uses in casting: historical core-powers-daily resolved path points to Omens, but current rule lost that line','Bilingual source-faithful reminders for selected combat/Character loop, including already-usable advancement','Armour restriction → Heretical Priest exception link'],'totalNeedsIncludingDependenciesUpperBound':16}
(p/'selection.json').write_text(json.dumps(selection,indent=2)+'\n')
lines=['# Batch 3 — triage and implementation gate','', 'Prepared at HEAD `11e86737cce0dac67c269537e07fedb84d189e97`, before production edits.','', 'All 401 inherited IDs were re-ranked using their existing matrix rows and current registry/code probes. This is triage, not a new 401-item source or browser audit. The original classifications are unchanged. Full per-ID scores and reasons: [triage-all.json](triage-all.json). Actual baseline: 50 browser queries, no campaign selected, no Campaign mutation; [browser-before.json](browser-before.json).','', 'Priority = frequency × interruption × relevance weight (Core general 1.3; rare cases discounted). Judgment limits implementation to 10 unique needs covering 19 audit IDs; six tightly bounded Core-loop dependencies keep the upper bound at 16, below 25. Price rows are one read-only purchase lookup, not ten new features.','', '## Top 30 remaining IDs','', '| Rank | Audit ID | Book · PDF / printed | Before | Frequency | Interruption | Relevance | Score | Why it matters | Minimal fix | Now? / reason |','|---|---|---|---|---:|---:|---|---:|---|---|---|']
for r in rows[:30]:
 yes=r['needId'] in selected
 reason='YES — verified everyday Core lookup' if yes else 'NO — outside this bounded Core set; defer rather than expand'
 vals=[r['rank'],r['needId'],f"{r['book']} · {','.join(map(str,r['pdfPage']))} / {r['printedPage']}",r['inheritedClassification'],r['playFrequency'],r['interruptionSeverity'],r['coreRelevance'],r['practicalPriority'],r['whyItMatters'],r['minimalFix'],reason]
 lines.append('| '+' | '.join(str(v).replace('|','/').replace('\n',' ') for v in vals)+' |')
lines+=['','## Selected scope','', '1. Full Core DR ladder in the existing Tests reference.','2. Core round duration and room-scale movement, with no invented metre allowance.','3. Food/water/starvation → existing Rest rule.','4. Infection → existing Rest rule, separate from RECLVSE by name.','5. Scroll equipment restrictions with the verified Heretical Priest exception.','6. Eight services/repair prices plus arrows and bolts in one concise lookup.','7–10. Four starting equipment definitions projected from existing verified rows: Bomb, Life elixir, Small but vicious dog, Monkeys.','', 'Dependencies: '+ '; '.join(selection['boundedDependencies'])+'.','', 'The baseline found `DR` and `round` returning class effects, `movement` absent, `starvation`/`infection`/`critical` pointing first to RECLVSE, and ordinary `flee` pointing only to SD. `negative HP` had no hit. Carrying, Rest, Broken, Getting Better and Omens are already usable under their known names; their mechanics are not counted as newly closed inherited IDs.','', 'Source verification is restricted to the selected pages and direct dependencies: [SOURCE-VERIFICATION.md](SOURCE-VERIFICATION.md). English stays primary and Korean is a separate concise helper. Existing generated/save data will not be regenerated.','', '## Explicit deferrals','', 'No treasure/relic catalog expansion, scenario creature expansion, advanced Mythic tools, additional RECLVSE systems, character creation automation, beasts purchase catalog, new campaign domain, or full-book re-audit. The three source-unavailable cases remain untouched.','', 'All unselected IDs retain inherited classification even where a static probe suggests an overlap was already addressed. Batch 3 closes only selected IDs that pass actual user-facing verification.']
(p/'BATCH3-TRIAGE.md').write_text('\n'.join(lines)+'\n')
print({'selectedIDs':len(selected),'uniqueNeeds':10,'upperBoundWithDependencies':16,'triaged':len(rows)})
