import type { RegionId } from '../domain/types';
import { regionById } from '../data/regions';

// Editorial tags affect selection only. They never rewrite a printed result.
export const REGION_BOOST = 1.25;
export const REGION_WEIGHT_TABLES = new Set([
  'core.status',
  'core.inhabitants',
  'core.feature',
  'core.danger',
  'core.rooms',
  'sd.room.adjective',
  'sd.room.type',
  'reclvse.dungeonPurposeThen',
  'reclvse.questEncounterHook',
  'reclvse.dungeonEntrance',
  'reclvse.entranceState',
  'reclvse.arcaneEncounter',
  'reclvse.dressing',
  'reclvse.roomPurpose',
]);
const lexicon: Record<string, readonly string[]> = {
  urban: [
    'city',
    'cities',
    'town',
    'towns',
    'street',
    'streets',
    'alley',
    'alleys',
    'market',
    'markets',
    'sewer',
    'sewers',
  ],
  cult: [
    'cult',
    'cults',
    'cultist',
    'cultists',
    'cathedral',
    'cathedrals',
    'temple',
    'temples',
    'priest',
    'priests',
    'ritual',
    'rituals',
    'worship',
  ],
  forest: [
    'forest',
    'forests',
    'woodland',
    'woodlands',
    'tree',
    'trees',
    'thicket',
    'thickets',
    'thorn',
    'thorns',
  ],
  grave: [
    'grave',
    'graves',
    'graveyard',
    'graveyards',
    'cemetery',
    'cemeteries',
    'tomb',
    'tombs',
    'crypt',
    'crypts',
    'chrypt',
    'catacomb',
    'catacombs',
    'sarcophagus',
    'sarcophagi',
    'burial',
  ],
  corpse: [
    'corpse',
    'corpses',
    'cadaver',
    'cadavers',
    'skeleton',
    'skeletons',
    'skeletal',
    'bone',
    'bones',
  ],
  coast: [
    'coast',
    'coastal',
    'shore',
    'shores',
    'sea',
    'ocean',
    'salt',
    'tide',
    'tidal',
    'drowned',
    'drowning',
    'harbor',
    'harbour',
  ],
  ruin: ['ruin', 'ruins', 'ruined', 'crumbling', 'collapsed'],
  ice: ['ice', 'icy', 'frozen', 'freezing', 'glacial', 'glacier'],
  frost: ['frost', 'frosted', 'frosty', 'snow', 'snowy', 'blizzard', 'winter'],
  wilderness: ['wild', 'wilderness', 'wasteland', 'barren', 'desolate'],
  cannibal: ['cannibal', 'cannibals', 'cannibalistic', 'cannibalism'],
  undead: [
    'undead',
    'zombie',
    'zombies',
    'wight',
    'wights',
    'lich',
    'liches',
    'vampire',
    'vampires',
    'ghost',
    'ghosts',
    'revenant',
    'revenants',
  ],
  plague: [
    'plague',
    'plagued',
    'pestilence',
    'disease',
    'diseased',
    'infected',
    'infection',
  ],
  root: ['root', 'roots', 'rooted'],
  cathedral: ['cathedral', 'cathedrals'],
  sewer: ['sewer', 'sewers'],
  authority: ['authority', 'priest', 'priests', 'ruler', 'guards'],
  beast: ['beast', 'beasts', 'wolf', 'wolves', 'animal', 'animals'],
  overgrowth: ['overgrown', 'overgrowth', 'brambles', 'vines', 'growth'],
  isolation: ['isolated', 'isolation', 'solitary', 'alone'],
  tomb: ['tomb', 'tombs', 'crypt', 'crypts', 'catacomb', 'catacombs'],
  funerary: ['funerary', 'funeral', 'burial', 'coffin', 'coffins'],
  suffocation: ['suffocating', 'suffocation', 'choking', 'airless'],
  melancholy: ['melancholy', 'sorrow', 'weeping', 'mourning'],
  nobility: ['noble', 'nobles', 'nobility', 'king', 'royal'],
  abandoned: ['abandoned', 'deserted', 'forsaken'],
  blood: ['blood', 'bloody'],
  glass: ['glass', 'obsidian'],
  lake: ['lake', 'lakes'],
  settlement: ['settlement', 'settlements', 'village', 'villages'],
  battlefield: ['battlefield', 'battlefields'],
  necromancy: ['necromancy', 'necromancer', 'necromancers'],
};
export function entryTags(text: string): string[] {
  const words = new Set(text.toLowerCase().match(/[a-z]+/g) ?? []);
  return Object.entries(lexicon)
    .filter(([, aliases]) => aliases.some((word) => words.has(word)))
    .map(([tag]) => tag);
}
export function regionWeightFactor(
  tableId: string,
  text: string,
  region?: RegionId,
): number {
  if (!region || !REGION_WEIGHT_TABLES.has(tableId)) return 1;
  const tags = entryTags(text);
  return regionById(region).tags.some((tag) => tags.includes(tag))
    ? REGION_BOOST
    : 1;
}
