"""Audit artifacts only: Mythic PDF124–230, current app snapshot vs supplied PDF.
No private source text is embedded: summaries below are audit findings.
"""
import json
from pathlib import Path
from collections import Counter
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'docs/pdf-escape-audit/data'
registry=json.loads((ROOT/'outputs/pdf-escape-audit/registry.json').read_text())
index=json.loads((ROOT/'outputs/pdf-escape-audit/reference-index.json').read_text())
source=json.loads((ROOT/'outputs/pdf-escape-audit/extracted/mythic.json').read_text())
rows=[]
code=['src/domain/mythic.ts:47','src/generators/mythic.ts:27','src/components/MythicPanel.tsx:181','src/domain/playReferenceRules.ts:334']
def add(key,pages,title,typ,state,problem,fix='None.',*,section='Variations',severity='P2',frequency=2,friction=4,queries=None,path=None,tableids=None,solutions=None,workflows=None,context='no',notes='',need=None):
 p=list(pages) if isinstance(pages,(list,range,tuple)) else [pages]
 green=state in ('RESOLVED','PDF_APPROPRIATE')
 if state=='PDF_APPROPRIATE':frequency=friction=None
 r=dict(id='mythic-extra-'+key,needId=need or 'mythic-'+key,bookId='mythic',book='Mythic Game Master Emulator Second Edition',pdfPage=p,printedPage=', '.join(str(x-1) for x in p),section=section,content=title,type=typ,classification=state,severity=None if green else severity,frequency=frequency,friction=friction,priority=frequency*friction if frequency and friction else None,appPath=path or ('Original supplied PDF' if state=='PDF_APPROPRIATE' else 'No usable application reference'),searchQueries=queries or [title],searchable='n/a' if state=='PDF_APPROPRIATE' else 'yes' if state=='RESOLVED' else 'indirect' if path else 'no',contextLinked='n/a' if state=='PDF_APPROPRIATE' else context,tableView='yes' if tableids else 'no' if typ=='Table' else 'n/a',problem=problem,minimalFix=fix,solutionType=solutions or ([] if state=='RESOLVED' else ['PDF_APPROPRIATE'] if state=='PDF_APPROPRIATE' else ['QUICK_RULE']),workflows=workflows or ['Solo'],evidence=dict(code=code,tableIds=tableids or [],notes=notes or 'Fresh supplied PDF body and repeated summary checked. Current registry has only two Mythic quick rules and no matching optional procedure. Fate state supports chart/check, Chaos, question, scene and bounded history only. Absence of a tracker is not itself a gap; missing usable rule/table is.'))
 rows.append(r);return r
add('preparation-advice',range(124,128),'Solo preparation, journaling approaches and piecemeal play','Long-form','PDF_APPROPRIATE','Organizing books, theater of mind, blogs and novelization are reading advice. These pages do not justify adding campaign diaries or automatic narrative writing.')
add('npc-statistics',[128,129,190,218],'Determining NPC Statistics','Procedure','MISSING','The generic Fate roller exists, but the statistic-result mapping and automatic Current Context special-condition branch are not exposed. This optional Mythic method starts with a player-chosen expected value; it is not verified MÖRK BORG creature data.','Add a concise optional rule with expected-value input interpretation and its five result branches. Never feed it into source-faithful monster presets as a missing-stat fallback.',queries=['NPC statistics','Does the NPC have a statistic value'],workflows=['NPC','Monster','Solo'])
add('sourcebook-advice',[129,130,131],'Sourcebooks: world building, lists and inspiration','Long-form','PDF_APPROPRIATE','Inspirational versus practical source use, list preparation and random shelf/book selection are long-form play advice, not missing fixed MÖRK BORG data.')
add('random-source-page',132,'Books as Random Tables','Procedure','PDF_APPROPRIATE','This optional technique intentionally sends the player to a random page of a chosen external sourcebook. The original book/PDF is the useful destination; automating a broad private-book sampler would add scope without removing this intended reading step.','Keep this advice and its random-page technique in the PDF; do not classify its deliberate PDF reading as an escape defect.')
add('thread-progress',[133,134,135,136,191,219],'Thread Progress Track: points, phases and Flashpoints','Procedure','MISSING','The optional 10/15/20-point rules, progress versus Flashpoint distinction, five-point phase checks, one Flashpoint per phase and timing are absent. Existing generic Threads are campaign notes, not this method.','Add one compact optional rule packet, usable with the paper track. No digital progress tracker or automatic narrative is required.',queries=['Thread Progress Track','Flashpoint'],frequency=3,friction=4)
add('thread-discovery-fate',[136,137,191,220],'Discovery Fate Question','Procedure','MISSING','The minimum odds, prerequisite discovery action and four Fate-answer branches are absent. Exceptional Yes combines two Discovery checks; Exceptional No prohibits another check this Scene. An ordinary Fate answer does not expose these consequences.','Add the short conditional rule and link the canonical Thread Discovery Check table once imported.',queries=['Discovery Fate Question','Is something discovered'],frequency=3,friction=4,solutions=['QUICK_RULE','RESULT_LINK'])
add('thread-discovery-table',[137,138,220],'Thread Discovery Check','Table','MISSING','The eight ranges of d10 plus current Progress, including the open-ended final range and Progress/Flashpoint/Track/Strengthen distinctions, are absent from the registry.','Import the actual eight-range table with a user-entered Progress modifier, preserving branch meaning; link existing Meaning tables without automatic prose.',queries=['Thread Discovery Check','Strengthen Progress'],frequency=3,friction=5,solutions=['TABLE_INDEX','TABLE_VIEW','PROCEDURE'],notes='PDF138 rendered and inspected: all eight ranges and explanatory left column complete; PDF220 duplicate checked. No source clipping or unavailable source.')
add('thread-conclusion',[138,139,140,141,191],'Thread Plot Armor and Conclusion','Rule','MISSING','The optional Focus Thread protection and removal at full progress are absent, including the delayed Conclusion exception that skips the next Expected Scene Chaos test. This is distinct from ordinary scene testing.','Add a short optional conclusion rule inside the Thread Progress packet. Preserve the player’s choice and ordinary MÖRK BORG lethality; do not enforce it globally.',queries=['Thread Plot Armor','Conclusion Thread Progress'],solutions=['QUICK_RULE','CONTEXT_LINK'])
add('thread-diversify',[141,142],'Diversifying Threads','Long-form','PDF_APPROPRIATE','Advice to split a goal into narrower related Threads is player organization, not an additional mandatory generator or social graph.')
add('player-knowledge',[142,143,144,145,221],'Player versus Character Knowledge','Rule','MISSING','The four-strategy summary is absent, including the mechanically consequential search/test-before-Fate ordering. Generic Oracle access does not explain when a hidden fact becomes established.','Add a concise optional strategy reference; retain examples and discussion in the PDF.',queries=['Player vs Character Knowledge','Test It Ask It'],severity='P3',frequency=2,friction=3)
add('conclusive-advice',[146,147],'Conclusive Adventure Conclusions','Long-form','PDF_APPROPRIATE','Move Toward A Thread is an application of Choosing Event Focus, already audited as mythic-choose-focus. Making the finale special is explicitly an attitude, not a new rule. No second missing procedure is counted.',notes='Cross-reference existing needId mythic-choose-focus for the mechanical option. Preserve source literary examples as reading material.')
for key,pp,title in [('mid-chaos-chart',[148,222],'Mid-Chaos Fate Chart'),('low-chaos-chart',[149,222],'Low-Chaos Fate Chart'),('no-chaos-chart',[149,222],'No-Chaos Fate Chart')]:
 add(key,pp,title,'Table','MISSING','Only the standard 81-cell Fate Chart is installed. This printed optional chart and its grouped Chaos columns are absent; keeping the ordinary Chaos number fixed does not provide all variant thresholds.','Add this exact optional chart behind deliberate source/table selection; retain standard Fate as the default.',queries=[title],frequency=2,friction=5,solutions=['TABLE_INDEX','TABLE_VIEW'],notes='Original PDF148–149 and duplicate PDF222 visually inspected. All thresholds present, including printed X and 99 limits. Current fateChart only sourcePage20/duplicate195, parser schema fixed to standard chart.')
for key,pp,title in [('mid-chaos-check',[148,223],'Mid-Chaos Fate Check Modifiers'),('low-chaos-check',[149,223],'Low-Chaos Fate Check Modifiers')]:
 add(key,pp,title,'Table','MISSING','The alternate grouped Chaos modifier table is absent; checkModifier always uses the standard full-strength modifier array.','Add the exact modifier table as optional quick reference and, if enabled later, keep its selected mode explicit.',queries=[title],frequency=2,friction=4,solutions=['TABLE_INDEX','TABLE_VIEW'])
add('hold-chaos',150,'No-Chaos questions and retained Scene/Event Chaos','Rule','MISSING','The option to remove Chaos only from Fate answers while retaining it for Scene and Random Event checks is absent. The source also permits player-chosen narrower Scene/Event Chaos ranges.','Include this short scope distinction with the alternate chart references. Do not implement No-Chaos by globally setting Chaos to zero.',queries=['No-Chaos questions','Hold the Chaos'],frequency=2,friction=3)
add('session-advice',[149,150],'What is a Session in Solo Play?','Long-form','PDF_APPROPRIATE','This is advice for relating another RPG’s session rewards to meaningful accomplishment. It does not mandate a Mythic timer, session diary or MÖRK BORG experience subsystem.')
add('keyed-scenes',[150,151,152,153,155,156,191],'Keyed Scenes: triggers, events and timing','Procedure','MISSING','The actual optional procedure is absent: player-defined trigger, next-Scene event, normal Expected/Altered/Interrupt handling, Current Context option, count/randomizer/frequency conditions and nullification.','Add a compact rules reference beside Scene tools. Let the paper notebook hold custom triggers and counts; do not build an automatic story scheduler.',queries=['Keyed Scenes','Keyed Scene Trigger'],frequency=2,friction=4)
add('keyed-scene-templates',[151,152,155],'Five sample Keyed Scene templates','Aid','MISSING','The source provides five labeled, operational examples (Let’s Rumble, Boss Fight, The Horror, Set Dungeon Tone, Stay On Schedule), with explicit conditions. No reference exposes these sample trigger/event packets.','Expose them as optional examples under the Keyed Scenes rule, keeping their source label and game-agnostic status. They are not default MÖRK BORG dungeon procedures.',queries=['Keyed Scene templates','Set Dungeon Tone','Boss Fight Mythic'],severity='P3',frequency=1,friction=3,solutions=['QUICK_RULE'])
add('keyed-sheet',[154,224],'Keyed Scenes Record Sheet','Aid','PDF_APPROPRIATE','Blank paper worksheet is suitable for printing beside the notebook. Its repeated appendix copy is the same aid, not a second missing feature.')
add('prepared-scaling',[158,159,191],'Prepared Adventure Scaling / Diminisher Value','Rule','MISSING','The source’s player-estimated scaling guideline for a solo PC is absent. It is explicitly approximate and may change encounter quantity OR individual power; it is not a fixed source stat block.','Add an optional quick reference preserving manual estimation and rounding. Never silently scale original MÖRK BORG creature definitions.',queries=['Diminisher Value','Prepared Adventure Scaling'],frequency=2,friction=4,workflows=['Solo','Dungeon','Monster'])
add('adventure-features',[159,160,161,165,192,225],'Prepared Adventure Features List and event interpretation','Procedure','PARTIAL','The canonical Prepared Adventure Focus table mentions the player-maintained Features List, but the usable reference does not describe selecting source-specific features or the optional Meaning step when a feature already determines the consequence.','Add the concise list/interpretation rule and link it from the existing Adventure Feature result. Keep list maintenance on paper; no settlement/faction system.',path='oracle:mythic2.prepared-adventure-event-focus-table → SOURCE (list named only)',queries=['Adventure Features','Adventure Feature'],frequency=2,friction=4,solutions=['QUICK_RULE','RESULT_LINK'])
add('prepared-scene-test',[160,161,162,163,164,165,192],'Prepared Adventure Scene Test and event routing','Procedure','PARTIAL','The replacement focus table is present, but the current Scene roller always chooses Altered/Interrupt within Chaos. The supplied prepared-adventure variant retains the Expected Scene and adds an event instead; it also uses the replacement focus table. That mode/procedure is unavailable.','Add a clear optional procedure reference connecting the existing table, and only an explicit variant roller if later authorized. Never substitute this behavior into the standard Scene test.',path='Mythic → Scene uses standard rule; separate oracle:mythic2.prepared-adventure-event-focus-table',queries=['Prepared Adventure Scene Test','Mythic prepared adventure'],frequency=3,friction=4,solutions=['PROCEDURE','CONTEXT_LINK','RESULT_LINK'],notes='PDF163 printed162 explicitly distinguishes adding Random Event from replacing Expected Scene. resolveScene lines107–115 uses only standard parity; MythicPanel eventClues lines146–165 always uses standard focus table.')
tid='mythic2.prepared-adventure-event-focus-table';t=next(t for t in registry['tables'] if t['id']==tid)
assert len(t['entries'])==7 and [(e['min'],e['max']) for e in t['entries']]==[(1,20),(21,40),(41,50),(51,55),(56,70),(71,80),(81,100)]
add('prepared-event-focus',[165,226],'Prepared Adventure Event Focus Table','Table','RESOLVED','All seven source d100 ranges and labels are present in the canonical registry. This table can be searched, rolled and intentionally inspected. The surrounding procedure is audited separately.',path='Reference Desk → oracle:'+tid+' → ROLL / TABLE',queries=['Prepared Adventure Event Focus Table'],tableids=[tid],frequency=3,friction=1,context='partial',notes='Source PDF165 printed164 and duplicatePDF226 printed225 checked directly. Current canonical table exactly matches all seven range boundaries and outcome identities.')
add('prepared-advice',[157,159,160,161,162,163,164,165,166],'Prepared Adventures: reading one detail at a time','Long-form','PDF_APPROPRIATE','Scenario text, spoilers, encounter examples and soft co-GM advice remain appropriate PDF reading. Numeric scaling and changed Scene procedure have separate gap rows; this exclusion does not hide them.')
add('features-sheet',[161,225],'Adventure Features List sheet','Aid','PDF_APPROPRIATE','The printable third-list sheet is an aid. Its usage rule is audited separately; no extra digital database is required.')
add('complicated-campaigns',[167,168,169,170],'Complicated Campaigns: pruning, fresh starts and multiple lists','Long-form','PDF_APPROPRIATE','Organization advice extends the existing I Dunno and List rules. Multiple paper lists and fresh narrative starts are elective practices, not missing campaign-management features.',notes='Links existing mythic-meaning-interpretation / mythic-lists / mythic-list-bookkeeping needs; no duplicate base-rule rows.')
add('peril-points',[171,172,192],'Peril Points','Rule','MISSING','The optional limited narrative-rescue resource, suggested initial pool and player choice of replenishment are absent. MÖRK BORG Omens are a different rule and do not resolve this lookup.','Add one short optional Mythic rule with manual paper bookkeeping; keep it distinct from Omens and do not add automatic rescues.',queries=['Peril Points'],severity='P3',frequency=1,friction=4)
add('crafter-integration',[172,173,174,175,176,192,227],'Adventure Crafter integration rules','Procedure','MISSING','The supplied Mythic text fully describes integration: Turning Points for opening/Interrupt only, Mythic Lists, immediate additions, full-list 2d10 invocation, empty-line choices and PC handling. None is exposed as a quick reference.','Add an optional integration reminder with a separate unavailable dependency notice for the external generation tables. Do not invent Turning Points.',queries=['Adventure Crafter Mythic','Turning Point Mythic'],severity='P3',frequency=1,friction=3)
add('crafter-source',[172,173,175],'Adventure Crafter Turning Point / Plot Point and Deck data','Source reference','SOURCE_UNAVAILABLE','This book refers to external Adventure Crafter generation tables and an optional deck; they are not printed here and no supplied file or installed canonical source contains them. The integration instructions themselves are available and separately audited.','Identify the external dependency clearly. Do not synthesize the absent Plot Point tables or count the separate product as missing MÖRK BORG data.',queries=['Adventure Crafter source','Adventure Crafter Deck'],severity='P3',frequency=1,friction=5,solutions=['SOURCE_MISSING'],notes='Current supplied inventory and Downloads filename search contain no Adventure Crafter source or deck. Mythic PDF172/175 explicitly identifies external products; PDF176/227 is only integration summary.')
add('support-art',[176,177,228,229,230],'Support resources, illustrations, patrons and cover','Long-form','PDF_APPROPRIATE','Credits, support/community links and illustrations are not reusable rule mechanics; no application counterpart is required.')
add('big-example',range(178,187),'The Big Example: Rapid Red playthrough','Long-form','PDF_APPROPRIATE','Nine-page worked superhero narrative demonstrates already audited Fate, Meaning, Lists and Scene tools. Its invented-in-example names and stats are not MÖRK BORG content to import.')
add('paper-journal',[77,193],'Adventure Journal sheet','Aid','PDF_APPROPRIATE','Printable scene journal belongs beside the handwritten notebook; reproducing it as an app chronology would conflict with product priorities.')

# Every physical page124–230 accounted for. Repeated mechanics point at original needs.
primary=json.loads((OUT/'mythic-rows.json').read_text())
all_ids={r['needId'] for r in primary+rows}
ledger=[]
for page in range(124,231):
 own=[r['needId'] for r in rows if page in r['pdfPage']]
 duplicate=[];theme='Variations / optional source material'
 if 178<=page<=186:theme='Worked example; no new generator source'
 if 187<=page<=192:
  theme='Rules Summary; repeat original procedures'
  duplicate={187:['mythic-fate-chart','mythic-fate-check'],188:['mythic-fate-rpg','mythic-event-focus','mythic-lists','mythic-first-scene'],189:['mythic-first-scene','mythic-scene-test','mythic-altered-followthrough','mythic-interrupt'],190:['mythic-npc-behavior','mythic-list-bookkeeping'],191:[],192:[]}[page]
 if page==194:theme='Repeated printable Adventure Lists';duplicate=['mythic-lists']
 if page==195:theme='Repeated standard Fate Chart';duplicate=['mythic-fate-chart']
 if page==196:theme='Repeated standard Fate Check';duplicate=['mythic-fate-check']
 if page==197:theme='Repeated Fate Questions as RPG rules';duplicate=['mythic-fate-rpg']
 if page==198:theme='Repeated Random Event Focus';duplicate=['mythic-event-focus']
 if page==199:theme='Repeated Choosing Event Focus';duplicate=['mythic-choose-focus']
 if 200<=page<=216:
  theme='Repeated Meaning tables; canonical entries counted only at their primary pages'
  ids=[t['id'] for t in registry['tables'] if t['id'].startswith('mythic2.meaning.') and page in t.get('duplicatePages',[])]
  duplicate=[r['needId'] for r in primary if set(r['evidence']['tableIds']) & set(ids)]
 if page==217:theme='Repeated expected Scene check and adjustment table';duplicate=['mythic-scene-test','mythic-altered-followthrough']
 if page==218:theme='Repeated NPC Behavior and Statistics';duplicate=['mythic-npc-behavior']
 if 219<=page<=227:theme='Collected variation tables/sheets; same need IDs as original pages'
 if page in [177,228,229,230]:theme='Art / credits / covers'
 # Primary audit names are resolved conservatively by known IDs, never manufactured.
 unresolved=[d for d in duplicate if d not in all_ids]
 duplicate=[d for d in duplicate if d in all_ids]
 ledger.append(dict(bookId='mythic',pdfPage=page,printedPage=str(page-1),section=theme,needIds=sorted(set(own+duplicate)),newNeedCounted=not (187<=page<=227),review='Fresh physical-page text reviewed; dense tables PDF138,148,149,165,222 additionally rendered. Appendix rows reuse primary need IDs.',unresolvedPrimaryNeedLinks=unresolved))
assert len(ledger)==107 and [p['pdfPage'] for p in ledger]==list(range(124,231))
assert len({r['id'] for r in rows})==len(rows)
assert all(r['classification'] in ['RESOLVED','PRESENT_BUT_INDIRECT','PARTIAL','MISSING','PDF_APPROPRIATE','SOURCE_UNAVAILABLE'] for r in rows)
for row in rows:
 assert all(t in {t['id'] for t in registry['tables']} for t in row['evidence']['tableIds'])
for name,obj in [('mythic-extra-rows.json',rows),('mythic-extra-page-ledger.json',ledger)]: (OUT/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'rows':len(rows),'pages':len(ledger),'classifications':dict(Counter(r['classification'] for r in rows)),'unresolvedLedgerIds':sorted({x for p in ledger for x in p['unresolvedPrimaryNeedLinks']})}))
