"""Record the root auditor's fresh PDF 1–123 review; does not mutate app data."""
import json
from pathlib import Path

OUT=Path('docs/pdf-escape-audit')
registry=json.loads(Path('outputs/pdf-escape-audit/registry.json').read_text())
index=json.loads(Path('outputs/pdf-escape-audit/reference-index.json').read_text())
search=json.loads(Path('outputs/pdf-escape-audit/table-search.json').read_text())
rows=[]
def add(key,title,pages,status='RESOLVED',kind='Procedure',path='',queries=(),problem='',fix='None.',severity=None,freq=3,fric=1,tables=(),solutions=(),context='partial',view='n/a'):
    rows.append(dict(id='mythic-'+key,needId='mythic-'+key,bookId='mythic',book='Mythic Game Master Emulator Second Edition',pdfPage=pages,printedPage=', '.join(str(p-1) for p in pages),section=title,content=title,type=kind,classification=status,severity=severity,frequency=freq if severity else None,friction=fric if severity else None,priority=freq*fric if severity else None,appPath=path or 'No dedicated reference',searchQueries=list(queries),searchable='yes' if status=='RESOLVED' else 'indirect' if status in ['PARTIAL','PRESENT_BUT_INDIRECT'] else 'no' if status=='MISSING' else 'n/a',contextLinked=context,tableView=view,problem=problem or 'Usable source content through the stated current route.',minimalFix=fix,solutionType=list(solutions),workflows=['Solo'],evidence={'code':['src/components/MythicPanel.tsx:109','src/generators/mythic.ts:17','src/components/ReferenceWorkbench.tsx:600','src/domain/referenceReading.ts:1'],'tableIds':list(tables),'notes':'Fresh supplied PDF text read by page; low-text pages visually checked. Printed pagination = PDF minus 1. Meaning tables counted once per conceptual lookup, not once per entry/roll/disclosure.'}))

add('fate-chart','Fate Questions: odds, Fate Chart and four answers',[18,19,20,21,24,25],path='Global MYTHIC FATE > Yes / No > Odds / CF > ROLL FATE',queries=['Fate Chart'],problem='Full numeric outcome is usable from the global panel, including manual dice. Desk search finds a reminder without a direct panel action; this extra routing inconvenience is recorded in SEARCH-AUDIT, not counted as a second missing rule.',view='indirect')
add('fate-check','Fate Check alternative: 2d10, modifiers and exceptional bands',[26,27],path='Global MYTHIC FATE > method Fate Check > ROLL FATE',queries=['Fate Check'],problem='Global panel offers full alternative resolution and manual dice even though universal search has no Fate Check entry.',view='indirect')
add('chaos','Chaos Factor: start, bounds and scene-end adjustment',[22,115],path='Global MYTHIC FATE > Chaos Factor',queries=['Chaos Factor'])
add('event-trigger','Random Event triggers from doubles and Interrupt Scene',[26,36,73],path='MYTHIC FATE result > 사건 단서 굴리기',queries=['random event'])
add('event-focus','Random Event Focus: twelve outcomes and referent selection',[37,38,39,40,41,42,43],status='PARTIAL',kind='Table',path='Desk > oracle:mythic2.random-event-focus-table; MYTHIC FATE event',queries=['Random Event Focus Table'],problem='Focus labels and Meaning rolls are present. NPC/Thread results do not explain which notebook list to consult; empty-list and selection rules are not available. Search random event also puts the prepared-adventure variant first.',fix='Add a concise focus interpretation/list-selection reminder alongside this existing table; preserve notebook ownership.',severity='P2',freq=3,fric=3,tables=['mythic2.random-event-focus-table'],solutions=['QUICK_RULE','RESULT_LINK','SEARCH_RANKING'],view='yes')
add('choose-focus','Choosing Event Focus instead of rolling; optional once-per-five-Scenes allowance',[43,44],status='MISSING',kind='Aid',queries=['Choosing Event Focus'],problem='The circumstance-to-focus reference and optional choice allowance are absent. Reading a visible focus row can replace a roll, but does not explain when the source permits choosing.',fix='Add a short optional-rule reminder linked from Event Focus; no choice-tracking subsystem.',severity='P3',freq=1,fric=2,solutions=['QUICK_RULE'])
add('lists','Notebook Adventure Lists: section dice, Choose blanks and empty-list Current Context',[45,46,47],status='MISSING',queries=['Adventure Lists','empty list'],problem='The event result can invoke a Thread/NPC but the 5-line section dice, blank Choose result and empty-list substitution are not explained in the app.',fix='One notebook-compatible list-selection Quick Rule, linked from Event Focus. Do not build a digital journal.',severity='P2',freq=3,fric=3,solutions=['QUICK_RULE','CONTEXT_LINK'])
add('action-pair','Meaning Tables: Actions pair',[47,48,52],kind='Table',path='Desk > procedure:mythic2.action-pair',queries=['Meaning Tables: Actions'],tables=['mythic2.meaning.action-1','mythic2.meaning.action-2'],view='yes')
add('description-pair','Meaning Tables: Descriptions pair',[47,49,52],kind='Table',path='Desk > procedure:mythic2.description-pair',queries=['Meaning Tables: Descriptions'],tables=['mythic2.meaning.descriptor-1','mythic2.meaning.descriptor-2'],view='yes')
for table in registry['tables']:
    if not table['id'].startswith('mythic2.meaning.') or table['id'].endswith(('action-1','action-2','descriptor-1','descriptor-2')): continue
    sid=table['id']; st=next(s for s in search if s['tableId']==sid)
    hit=next((i+1 for i,r in enumerate(st['results']) if sid in r['canonicalIds']),None)
    pages=[table['sourcePage']]
    if sid.endswith('.characters'):pages.append(89)
    if sid.endswith('.locations'):pages.append(97)
    if sid.endswith('.objects'):pages.append(99)
    add(sid.replace('mythic2.meaning.','meaning-'),table['title']+' — Elements Meaning pair',pages,status='RESOLVED' if hit and hit<=3 else 'PRESENT_BUT_INDIRECT',kind='Table',path=f'Desk > oracle:{sid}; procedure:{sid}.pair',queries=[table['title'],table['title']+' Meaning pair'],problem=f'Complete 100-entry source table, pair procedure and inspector. Exact table heading has canonical route at rank {hit or "outside top five"}; single-roll and pair actions coexist. Player interprets the words.',fix='None.' if hit and hit<=3 else 'Add a book-qualified alias to this existing table/pair; no new generator.',severity=None if hit and hit<=3 else 'P2',freq=2,fric=2,tables=[sid],solutions=[] if hit and hit<=3 else ['SEARCH_ALIAS','SEARCH_RANKING'],view='yes')
add('meaning-interpretation','Choosing Meaning / doubling identical words / mining for meaning / I Dunno',[51,52,53,54,55,85,86,87,103,104,105,106,107],status='PDF_APPROPRIATE',kind='Long-form',problem='Interpretation advice, worked illustrations and flexible use of fragments. Existing tables supply the prompts; narration remains the player’s task.',fix='Keep the original explanation in the PDF; an optional reading link is sufficient.',solutions=['PDF_APPROPRIATE'],context='n/a')
add('first-scene','First Scene: inspired idea, random event, Meaning and 4W alternatives',[64,65,66,67],status='PARTIAL',path='Desk > procedure:mythic2.the-4w',queries=['The 4W'],problem='The 4W procedure works, but its presence does not explain the alternative first-scene methods or that the first scene is not tested against Chaos.',fix='Add a short first-scene reminder to the existing 4W/scene references; retain optional strategies and player interpretation.',severity='P2',freq=2,fric=3,tables=['mythic2.meaning.characters','mythic2.meaning.action-1','mythic2.meaning.action-2','mythic2.meaning.locations'],solutions=['QUICK_RULE'])
add('scene-test','Testing the Expected Scene',[68],path='MYTHIC FATE > 장면 판정; Desk > rule:mythic2.scene-test',queries=['Altered Scene','Interrupt Scene'])
add('altered-followthrough','Altered Scene: next expectation or optional Scene Adjustment',[68,69,70,71,72,73],status='PARTIAL',path='MYTHIC FATE > Altered result; separate oracle:mythic2.scene-adjustment-table',queries=['Scene Adjustment Table'],problem='Scene Check reports Altered but does not explain its next-most-expected meaning or offer a direct Scene Adjustment link. The separate table has only outcome labels: 7–10 Make 2 Adjustments omits repeat/conflict handling.',fix='Add a concise next-step reminder/link and the source’s reroll/conflict rule to the existing adjustment table.',severity='P1',freq=3,fric=3,tables=['mythic2.scene-adjustment-table'],solutions=['QUICK_RULE','RESULT_LINK','PROCEDURE'],view='yes')
add('interrupt','Interrupt Scene: Random Event Focus + Meaning',[73,74],path='MYTHIC FATE > Interrupt > 사건 단서 굴리기',queries=['Interrupt Scene'],problem='Panel provides the event-clue action. List-selection guidance is a separate missing need counted in mythic-lists.')
add('automatic-interrupt','Automatic Interrupt to unstick play; optional Move Toward A Thread',[80,81],status='MISSING',queries=['Automatic Interrupt'],problem='No concise reference explains bypassing the scene test or fixing Event Focus when stuck.',fix='Add a brief optional reminder and link to existing Focus/Meaning tables.',severity='P2',freq=2,fric=3,solutions=['QUICK_RULE','RESULT_LINK'])
add('npc-behavior','NPC Behavior Table: Yes/No/Exceptional/Random Event interpretation',[107,108,109,110,111,112],status='MISSING',kind='Rule',queries=['NPC behavior'],problem='Many NPC inspiration tables exist, but this specific outcome-to-action reminder is absent. The Random Event branch fixes Current Context and supplements the NPC action; generic event focus rolling is not the same procedure.',fix='Index the short NPC Behavior reminder with links to the existing Character Action/Conversation tables; no behavior automation.',severity='P1',freq=3,fric=3,solutions=['QUICK_RULE','CONTEXT_LINK'])
add('list-bookkeeping','End-of-Scene notebook list weighting, removals and full-list cleanup',[112,113,114],status='MISSING',queries=['End of Scene','bookkeeping'],problem='The maximum three entries per element and full-list consolidation rule are absent. Optional app Threads are not a reference for this paper-list procedure.',fix='A concise notebook list-maintenance reminder with exact source; no narrative logging feature.',severity='P2',freq=3,fric=2,solutions=['QUICK_RULE'])
add('chaos-variants','Revert Toward the Mean / Random Chaos optional adjustments',[115],status='MISSING',queries=['Random Chaos'],problem='Panel states only the normal control-based adjustment. The two source alternatives are not retrievable.',fix='A compact optional-rule disclosure in the existing Chaos reference.',severity='P3',freq=1,fric=3,solutions=['QUICK_RULE'])
add('fate-rpg','Fate Questions as replacement RPG resolution',[31],status='MISSING',kind='Rule',queries=['Fate Questions RPG'],problem='The optional CF5, normally ignore exceptional/random events rule is absent. It is not a replacement for missing MÖRK BORG combat rules in this audit.',fix='A small optional Mythic rule reminder only if users choose this variant.',severity='P3',freq=1,fric=2,solutions=['QUICK_RULE'])
add('examples','Introductions, interpretation, scene framing and three extended worked examples',[2,4,8,9,10,11,12,13,14,15,16,23,28,29,30,32,33,55,56,57,60,61,62,63,74,75,76,78,79,80,81,82,83,84,103,104,105,106,111,116,117,118,119,120,121],status='PDF_APPROPRIATE',kind='Long-form',problem='Long-form examples and contextual guidance are appropriate reading. Mechanical sidebars on these pages are assessed separately above.',fix='Keep long-form examples in the book.',solutions=['PDF_APPROPRIATE'],context='n/a')
add('art-and-forms','Cover/art, contents and printed layout aids',[1,3,5,6,7,17,34,35,46,58,59,122,123],status='PDF_APPROPRIATE',kind='Aid',problem='Artwork and printable notebook sheets are intentionally book/PDF material; no need to replace the handwritten record.',fix='None.',solutions=['PDF_APPROPRIATE'],context='n/a')
OUT.joinpath('data/mythic-rows.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')

ranges=[(1,7,'Cover, credits, contents and artwork'),(8,16,'Introduction and how Mythic works; underlying Fate/Scene mechanics counted at their full rules'),(17,17,'Artwork'),(18,27,'Fate question, chart/check, odds and event trigger rules'),(28,30,'Fate interpretation and expectations discussion'),(31,31,'Optional Fate-as-RPG rule'),(32,33,'Henny example; no new lookup'),(34,35,'Artwork'),(36,44,'Random Event trigger/focus/choosing and interpretation'),(45,47,'Lists as tables; empty/Choose rules; Meaning procedure'),(48,50,'Action, Description and three core Elements tables'),(51,54,'Meaning selection, doubled words, interpretation/mining'),(55,57,'I Dunno advice and Wutwo Labs example'),(58,59,'Artwork'),(60,63,'Scene structure/list preparation and interpretation guidance'),(64,67,'First Scene strategies and 4W'),(68,74,'Expected/Altered/Interrupt scene rules and adjustment table'),(75,76,'Play-out example and scene-boundary guidance'),(77,77,'Printable Adventure Journal'),(78,84,'Scene boundary strategies, automatic interrupt and question guidance'),(85,87,'Discovering Meaning and table-use guide'),(88,102,'All 45 Elements tables, including three repetitions; compared to installed canonical table headings and entries'),(103,107,'Specific table-use explanations; Names sound/concept interpretation; NPC behavior introduction'),(108,112,'NPC Behavior rule/table, conversations, social skills and bookkeeping start'),(113,115,'List update/removal/cleanup, Chaos adjustment and alternatives'),(116,121,'Guardian example; existing procedures illustrated'),(122,123,'Artwork')]
ledger=[]
for page in range(1,124):
    title=next(s for a,b,s in ranges if a<=page<=b)
    ledger.append({'pdfPage':page,'printedPage':str(page-1) if page>7 else None,'review':title,'relatedNeeds':[r['needId'] for r in rows if page in r['pdfPage']],'method':'fresh full text; low-text art/form pages also rendered'})
OUT.joinpath('data/mythic-main-page-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n')
print(len(rows),'Mythic main unique needs; 123 physical pages reviewed')
