"""Materialize the FER/HER audit, using current private inventory for IDs only.

Read-only application audit. No source payload is copied into tracked reports.
Judgments below were made from fresh extraction and selected PDF renders, not
from pre-existing source-status flags. Run after inspect_registry.ts.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'docs/pdf-escape-audit/data'
pack = json.loads((ROOT / 'outputs/morkborg-private-data.json').read_text())
registry = json.loads((ROOT / 'outputs/pdf-escape-audit/registry.json').read_text())
index = json.loads((ROOT / 'outputs/pdf-escape-audit/reference-index.json').read_text())
tables = {t['id']: t for t in registry['tables']}
references = {r['id']: r for r in index}
rows = []
BOOKS = {'feretory': 'MÖRK BORG CULT: FERETORY', 'heretic': 'MÖRK BORG CULT: HERETIC', 'dark-fort': 'DARK FORT', 'dark-fort-sheet': 'DARK FORT SHEET', 'feretory-sv': 'MBC FERETORY Svenska texter', 'death-ziggurat-map': 'The Death Ziggurat — Player Map'}

def slug(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')

def add(book, key, pages, section, content, typ, state, problem, fix='None.', *, severity='P2', frequency=2, friction=3, path='', queries=None, tableids=None, code=None, solutions=None, workflows=None, printed=None, notes='', need=None, searchable=None, context='no', view=None):
    pages = list(pages) if isinstance(pages, (list, range, tuple)) else [pages]
    if printed is None:
        printed = ', '.join(str(p - 2) for p in pages) if book in ['feretory', 'heretic'] and all(p >= 5 and p < 66 for p in pages) else 'Unnumbered / fold or cover; see page ledger'
    green = state in ['RESOLVED', 'PDF_APPROPRIATE']
    if state == 'PDF_APPROPRIATE': frequency = friction = None
    row = dict(id=f'{book}-{key}', needId=need or f'{book}:{key}', bookId=book, book=BOOKS[book], pdfPage=pages, printedPage=printed, section=section, content=content, type=typ, classification=state, severity=None if green else severity, frequency=frequency, friction=friction, priority=frequency*friction if frequency and friction else None, appPath=path or ('Original supplied PDF' if state == 'PDF_APPROPRIATE' else 'No usable application reference'), searchQueries=queries or [content], searchable=searchable or ('n/a' if state == 'PDF_APPROPRIATE' else 'no' if not path else 'yes' if state == 'RESOLVED' else 'indirect'), contextLinked='n/a' if state == 'PDF_APPROPRIATE' else context, tableView=view or ('yes' if tableids else 'n/a'), problem=problem, minimalFix=fix, solutionType=solutions or ([] if state == 'RESOLVED' else ['PDF_APPROPRIATE'] if state == 'PDF_APPROPRIATE' else ['QUICK_RULE']), workflows=workflows or ['Dungeon'], evidence={'code': code or ['src/domain/references.ts:405', 'src/domain/references.ts:903'], 'tableIds': tableids or [], 'notes': notes or 'Fresh supplied PDF page text checked against current private bundle, canonical registry and display path. Browser checks are reported separately by the coordinating audit.'})
    rows.append(row)
    return row

def table(book, tid, section, *, state='RESOLVED', problem=None, fix='None.', **kwargs):
    t = tables[tid]
    p = t.get('sourcePage') or t.get('sourcePages')
    if isinstance(p, str): p = [int(n) for n in re.findall(r'\d+', p)]
    return add(book, 'table-'+tid.split('.',1)[1].replace('.', '-'), p, section, t['title'], 'Table', state, problem or 'All table outcomes, dice and relevant effect text are present; canonical reference supports rolling or intentional full-table inspection. A completed table does not imply every surrounding scenario rule is covered.', fix, path='Reference Desk → oracle:'+tid+' → ROLL / TABLE / SOURCE', queries=[t['title']], tableids=[tid], printed=str(t.get('printedPage') or 'Unnumbered fold / cover'), frequency=2, friction=1 if state == 'RESOLVED' else 3, **kwargs)

# FERETORY front fold and the daily journey tools.
add('feretory','monster-approaches',[2,3],'The Monster Approaches','Three-die monster procedure and derived statistics','Procedure','RESOLVED','A/B/C use three retained d12s; greatest Morale, lowest-die damage and highest-table armor derive from those rolls. HP follows the literal doubled single damage-die instruction. The contradictory printed 2d8 example and armor ties are disclosed, not silently reconciled.',path='Reference Desk → oracle:feretory.A → ROLL → SOURCE',tableids=['feretory.A','feretory.B','feretory.C'],code=['src/generators/feretory.ts:1','src/domain/referenceReading.ts:20'],frequency=4,friction=1,workflows=['Monster'],printed='Inside front cover; unnumbered',context='yes')
for tid in ['feretory.desire','feretory.trait']:
    table('feretory',tid,'The Monster Approaches',workflows=['Monster'],context='yes')
add('feretory','travel-distances',6,'Roads to Damnation','Named-route travel durations and world/weather scaling','Rule','MISSING','PDF map contains eleven route dice and explicit smaller/larger world and bad-weather adjustments. Current Roads reference cites PDF6 but states no travel durations; no route-value data or usable lookup exists. A citation is insufficient.', 'Add a compact source map-route table with endpoints, dice, scaling and weather note. Keep the illustrated map as an optional PDF aid.',severity='P1',frequency=4,friction=5,path='Reference Desk → rule:feretory.roads (citation only)',queries=['travel distance','Galgenbeck Schleswig','travel time'],solutions=['QUICK_RULE','TABLE_INDEX','CONTEXT_LINK'],workflows=['Travel'],printed='4',code=['src/domain/references.ts:299'])
add('feretory','travel-checklist',7,'Roads to Damnation','Daily checklist, road events and one-off event replacement','Procedure','RESOLVED','Calendar/weather/activity ordering, repeated forks, weather changes and tracking crossed-out events have usable Journey controls and source procedures. Replacements remain player-authored; no source fiction is invented.',path='Journey → Dawn → Road / Forage → encounter → Camp; rule:feretory.roads',tableids=['feretory.roadType','feretory.roadEvent'],code=['src/domain/journeyProcedure.ts:120','src/domain/referenceGeneratorProcedures.ts:118','src/components/JourneyWorkbench.tsx:310'],frequency=5,friction=1,workflows=['Travel','Solo'],context='yes')
for tid in ['feretory.roadType','feretory.roadEvent','feretory.village','feretory.forage','feretory.leaveRoad','feretory.campsite']:
    table('feretory',tid,'Roads to Damnation',workflows=['Travel'],context='yes')
add('feretory','epk-hunting-rules',12,'Eat Prey Kill','Hunting test, quantities, edible yield and optional mundane-prey dice','Procedure','PARTIAL','The quick rule covers Presence, regional d6, failure mishap, parenthesized quantity and HP-based rations. It omits the printed optional d8/d10/d12 with 7+ mundane prey. No need to automate the optional rule, but the in-app hunting reference is incomplete.', 'Add the short optional wider-die clause to hunting SOURCE/rule detail and link each canonical regional table.',severity='P2',frequency=4,friction=3,path='rule:feretory.hunting-procedure / procedure:workbench.epk',queries=['hunting','Eat Prey Kill'],tableids=['feretory.huntingMishaps','feretory.bellyOfBeast'],code=['src/domain/playReferenceRules.ts:102','src/generators/monster.ts:615'],solutions=['QUICK_RULE','RESULT_LINK'],workflows=['Travel','Monster'],context='partial')
for tid in ['feretory.huntingMishaps','feretory.bellyOfBeast']:
    table('feretory',tid,'Eat Prey Kill',workflows=['Travel','Monster'],context='yes')

# Check every regional creature independently, including stat-less source faces.
shared = {'Half-Billed Raven':'creature:half-billed-raven','Unbred Mutts':'creature:unbred-mutt','Twice-Grown Corpse Flies':'creature:twice-grown-corpse-fly'}
for c in pack['library']['creatures']:
    if c.get('book') != 'feretory': continue
    name=c['name']; ref=next((r['id'] for r in index if r['kind']=='creature' and r['id'].endswith(c['id'])), '')
    state='RESOLVED'; problem='Fixed source identity, printed stat values, attack and printed special/description mechanics are usable through direct creature lookup. No unprinted attack or armor was inferred.'; fix='None.'
    if name == 'Carcasswan':
        state='PARTIAL';problem='Both lone and paired printed stat blocks are in record.variants, but loadMonsterPreset and Reference result omit variants and show an unavailable generic stat block. The source DOES supply these stats.';fix='Expose the two labeled source variants from the existing record without substituting or rerolling them.'
    elif name == 'Lentil Lice':
        problem='Source supplies no lice combat stats; withholding them is correct. The separate printed starved-peasant encounter is audited separately because participants metadata is not displayed.'
    elif name == 'Cursed Trout':
        problem='Source supplies an insomnia effect, no independent combat stats. The full effect is retained and readable. Blank stats are legitimate source absence, not an implementation gap.'
    add('feretory','creature-'+c['id'].split('.')[-1],c['pdfPage'],'Eat Prey Kill',name,'Creature',state,problem,fix,path='Reference Desk → '+ref,queries=[name],code=['src/domain/references.ts:557','src/domain/referenceExecution.ts:61','src/generators/monster.ts:362'],solutions=['MONSTER_REFERENCE'] if state!='RESOLVED' else [],frequency=3,friction=1 if state=='RESOLVED' else 4,workflows=['Monster','Travel'],printed=str(c['printedPage']),context='partial' if c['regionKey'] in ['lakeOnda','bergen'] else 'yes',need=shared.get(name))
add('feretory','epk-starved-peasants',17,'Eat Prey Kill / Lentil Lice','Starved peasants','Creature','PARTIAL','Printed peasant stats are correctly separated from lice in record.participants, but neither direct reference nor creature result exposes that participant stat block.', 'Add a source participant link/compact stat block from the existing metadata, preserving d6 quantity and lice identity.',path='Lentil Lice → participants data currently omitted',queries=['Starved peasants','Lentil Lice'],solutions=['MONSTER_REFERENCE','RESULT_LINK'],frequency=3,friction=4,code=['src/generators/monster.ts:362','src/domain/referenceExecution.ts:61'],workflows=['Monster','Travel'])
add('feretory','epk-farmers',19,'Eat Prey Kill / Schleswig Bogfeeder','Farmers defending their pigs','Creature','PRESENT_BUT_INDIRECT','All quick stats and conditional weapon chance are visible inside Bogfeeder specialAbility, but farmers have no own lookup or contextual identity.', 'Index the existing nested encounter as an alias/sub-result; do not invent a separate general farmer.',path='Reference Desk → Schleswig Bogfeeder → Special',queries=['Schleswig Bogfeeder','farmers'],solutions=['MONSTER_REFERENCE','SEARCH_ALIAS'],frequency=2,friction=2,workflows=['Monster','Travel'])
add('feretory','epk-regular-wolf',23,'Eat Prey Kill / Überwolf','Regular wolf accompanying Überwolf','Creature','PARTIAL','Printed companion stats are in record.companions/sourceNotes. Reference result omits both; only the larger Überwolf stats and follower-count prose are visible.', 'Expose the existing labeled companion block and quantity qualifier; do not use Überwolf stats for regular wolves.',path='Reference Desk → Überwolf (companion data omitted)',queries=['Regular wolf','Überwolf'],solutions=['MONSTER_REFERENCE','RESULT_LINK'],frequency=3,friction=4,code=['src/generators/monster.ts:519','src/domain/referenceExecution.ts:61'],workflows=['Monster','Travel'])
add('feretory','epk-regional-access',range(14,24),'Eat Prey Kill','Nine regional d6 source tables → selected creature definition','Procedure','PRESENT_BUT_INDIRECT','Nine canonical region tables exist, including Lake Onda and Bergen Chrypt. The generic table result is an identity, not the creature stat block; table related links do not route to each creature. The seven-region EPK tool is faster for its supported regions.', 'Link each rolled canonical creature ID to its current definition, including the source-only and variant cases.',path='oracle:feretory.hunting.{region}; procedure:workbench.epk',queries=['Lake Onda','Bergen Chrypt','Eat Prey Kill'],tableids=[t for t in tables if t.startswith('feretory.hunting.')],code=['src/data/oracles/index.ts:187','src/generators/monster.ts:615','src/domain/references.ts:446'],frequency=3,friction=3,solutions=['RESULT_LINK','CONTEXT_LINK'],workflows=['Monster','Travel'])

# Source scenario table bodies can be present even where creatures/procedures are not.
for tid in ['feretory.flowerEffects','feretory.ruinTypes','feretory.minorTreasures','feretory.majorTreasures','feretory.searchingRuins','feretory.ruinsRandomEvents']:
    table('feretory',tid,'The Death Ziggurat')
add('feretory','ziggurat-procedure',[27,28,29],'The Death Ziggurat','Hex exploration, searching and conditional results','Procedure','PRESENT_BUT_INDIRECT','One hex/15 minutes, per-hex events, search table and restricted d6/d10 event branches are split between tables/source notes. Secondary treasure and named creature results lack direct links; players must independently find them.', 'Add one concise scenario procedure reference linking the existing tables and named actors; preserve d6/d10 restricted event branches. Map and location prose remain PDF material.',path='Reference Desk → Searching the Ruins / Random Events → SOURCE',queries=['Death Ziggurat','Navigating the Ruins'],tableids=['feretory.searchingRuins','feretory.ruinsRandomEvents','feretory.minorTreasures','feretory.majorTreasures'],solutions=['PROCEDURE','RESULT_LINK'],frequency=2,friction=3)
for name,pages in [('Rot Priests',32),('Horn Beasts',32),('Undead — Death Ziggurat',32),('Sarku',32),('Death-obsessed Cultist',33),('Dread Akünh, Demon Spawn',33)]:
    add('feretory',slug(name),pages,'The Death Ziggurat',name,'Creature','MISSING','Scenario supplies its own stat block and special combat rules; no definition exists in current creature data. Related event table mentions are only names.', 'Add the printed scenario-specific definition and link its event-table occurrences; never substitute the similarly named Core creature.',solutions=['MONSTER_REFERENCE','RESULT_LINK'],frequency=2,friction=5,workflows=['Dungeon','Monster'])
for key,title,pp,problem in [
 ('spiral-crown','Spiral Crown',30,'The artifact’s removal tests, three-attempt limit and drain/reversal effect are absent.'),
 ('rot-priest-medallion','Rot priest medallion', [30,32],'The item that enables access to the Death Realm is not represented.'),
 ('akuenh-heart','Akünh’s separated heart and end condition',30,'The heart-destruction consequence and immediate Misery trigger are absent from any usable quick reference.')]:
    add('feretory',key,pp,'The Death Ziggurat',title,'Item' if key!='akuenh-heart' else 'Rule','MISSING',problem,'Add a concise scenario-bound reference and source link; retain discovery/location prose in the PDF.',solutions=['ITEM_REFERENCE'] if key!='akuenh-heart' else ['QUICK_RULE'],frequency=2,friction=5)
table('feretory','feretory.itemsTrinkets','d100 Items & Trinkets',workflows=['Equipment','Dungeon'])
table('feretory','feretory.goblinGrinderHooks','The Goblin Grinder')
add('feretory','calumny-pearl',38,'The Goblin Grinder','Calumny Pearl','Item','PRESENT_BUT_INDIRECT','Its complete effect is retained in hook result 4; item name is not indexed separately.', 'Expose a named item alias opening that existing source entry.',path='oracle:feretory.goblinGrinderHooks → TABLE → row 4',tableids=['feretory.goblinGrinderHooks'],solutions=['ITEM_REFERENCE','SEARCH_ALIAS'])
for name,pages in [('Qarg',39),('Nagel Krat',[39,48]),('The Bastard',[39,48]),('Excited cannon goblins',45),('Archer goblins and bucket goblin',46),('Alchemical Ooze',47),('Fresh Goblins',48)]:
    add('feretory',slug(name),pages,'The Goblin Grinder',name,'Creature','MISSING','Printed local stats and special/variant conditions are absent; generic Core goblins do not have the same morale, attacks or leader effects.', 'Add the exact scenario stat block/variant and link relevant local tables.',solutions=['MONSTER_REFERENCE','RESULT_LINK'],frequency=2,friction=5,workflows=['Dungeon','Monster','NPC'])
for name in ['Goblin Cure','Flash Powder','Healing Tincture','Invigorating Elixir']:
    add('feretory',slug(name),41,'The Goblin Grinder / Medickal Shoppe',name,'Item','MISSING','The named purchasable item has an explicit price and operational benefit/risk in the source; no usable item effect exists in the installed data.', 'Add a compact item reference with its exact price, effect, duration and risk; keep the vendor setting in PDF.',solutions=['ITEM_REFERENCE'],workflows=['Equipment','City'],frequency=2,friction=5)
add('feretory','urvan-remedy',45,'The Goblin Grinder / Basement','Urvan’s alchemical pain remedy','Item','MISSING','The healing amount and temporary Presence penalty are absent.', 'Add the short source effect as a scenario item reference.',solutions=['ITEM_REFERENCE'],frequency=2,friction=4,workflows=['Equipment','Dungeon'])
for key,pp,title,problem in [
 ('cannon-hazard',[42,44,45],'Cannon fuse, warning test and firing consequences','The one-minute countdown, warning test, line-of-fire death and alarm consequences have no in-app quick rule.'),
 ('oil-fire',46,'Oil coating and fire damage','The added flame damage and action to remove oil are absent.'),
 ('grinder-operation',[42,45,47,48],'Goblin Grinder activation and escalation','The per-delay creation rule, final goblin count and two-action activation requirements are absent.')]:
    add('feretory',key,pp,'The Goblin Grinder',title,'Rule','MISSING',problem,'Add a source-bound local hazard/procedure reminder; do not create a general campaign simulator.',solutions=['QUICK_RULE'],frequency=2,friction=4)
for tid in ['feretory.lickLiquid','feretory.alchemyTables']:
    table('feretory',tid,'The Goblin Grinder')
add('feretory','alchemy-trigger',47,'The Goblin Grinder / Laboratory','Alchemy-table trigger and ooze exception','Procedure','RESOLVED','Each-round d6 1–2 trigger and ooze exception are present in table sourceNote; d4 effects are complete. Manual handling is sufficient; no automatic multi-step roller is required for coverage.',path='oracle:feretory.alchemyTables → SOURCE',tableids=['feretory.alchemyTables'],frequency=2,friction=2)

# Individual named relics: full effect text exists, but universal search does not index rows.
t=tables['feretory.tenebrousReliquary']
for i,e in enumerate(t['entries']):
    name=e['text'].split(' by ')[0]
    add('feretory','relic-'+str(e['min']),50+i//6,'The Tenebrous Reliquary',name,'Item','PRESENT_BUT_INDIRECT','Complete source item effect is retained in the canonical d66 row. Universal reference search does not index entry text, so the user must know the collection and locate the row; random generation is not retrieval.', 'Index the existing named source row as an item alias, opening/highlighting it without duplicating its text.',path=f'oracle:feretory.tenebrousReliquary → TABLE → {e["min"]}',queries=[name,'Tenebrous Reliquary'],tableids=['feretory.tenebrousReliquary'],solutions=['ITEM_REFERENCE','SEARCH_ALIAS','RESULT_LINK'],workflows=['Equipment','Powers'],frequency=3,friction=3)
for tid in ['feretory.selectMenu','feretory.cheapMenu','feretory.innkeeperTwitch','feretory.patronTraits','feretory.moreLostSouls']:
    table('feretory',tid,'Grey Galth Inn',workflows=['City','NPC'],context='yes')
add('feretory','three-dead-skulls',57,'Grey Galth Inn','Three Dead Skulls complete betting/payout rules','Procedure','PARTIAL','Current quick reference explicitly stops short of payouts, coward reroll, cheating/fight/death consequences and prizes, directing the user to printed55. A basic 3d6 button is not a playable gambling procedure.', 'Add the compact printed combination/payout matrix and complete side conditions as a static rule. Automation is optional and must follow verified die pictures.',path='rule:feretory.three-dead-skulls',queries=['Three Dead Skulls','gambling'],code=['src/domain/playReferenceRules.ts:19'],solutions=['QUICK_RULE','TABLE_INDEX'],workflows=['City'],frequency=3,friction=5,printed='55',context='yes',notes='Fresh PDF57 rendered to inspect winning die faces; the supplied page is complete.')
for name in ['Gambling Dreg','Hardy Tame Rat']:
    add('feretory',slug(name),57,'Grey Galth Inn',name,'Creature','MISSING','Full source stat block and, for the rat, lethal bite/feed/abandonment mechanics are absent. The inn reference is not a stat reference.', 'Add the named inn creature and link it from the gambling rule.',solutions=['MONSTER_REFERENCE','RESULT_LINK'],workflows=['City','Monster'],frequency=2,friction=5)
for d in pack['library']['notes']['characterClasses']['classes']:
    b=d['source']['bookId']
    if b not in ['feretory','heretic']: continue
    tid=[s['tableId'] for s in d['features'] if 'tableId' in s]
    add(b,'class-'+d['id'],d['source']['pdfPages'],'Supplement character class',d['name'],'Class','PRESENT_BUT_INDIRECT','Source creation formulas, permitted equipment, class rules and complete feature results exist in the class manifest/canonical tables and generated Character sheet. Universal lookup returns fragment tables, not a complete class reference; viewing an unchosen class requires generation/selection context.', 'Expose a read-only class reference from the existing manifest with links to all features; retain the normal Character generator.',path='Characters → New → class selection → generated sheet → 직업 능력',queries=[d['name']],tableids=tid,code=['src/generators/characterClasses.ts:83','src/generators/characterClasses.ts:360','src/components/Characters.tsx:602'],solutions=['CLASS_REFERENCE','SEARCH_ALIAS'],workflows=['Character'],frequency=3,friction=3,printed=', '.join(str(p) if p is not None else 'fold' for p in d['source'].get('printedPages',[])),context='partial')
for tid in ['feretory.skinwalkerFirstDied','feretory.skinwalkerShapes','feretory.paleOneOrigins','feretory.paleOneBlessings','feretory.deadGodGifts','feretory.philosopherDejection','feretory.philosopherRoots','feretory.philosopherItem']:
    table('feretory',tid,'Supplement class tables',workflows=['Character'],context='yes')
for ids,title,p in [(['feretory.paleNameA','feretory.paleNameB','feretory.paleNameC'],'Pale One name: three independent d20 columns',60),(['feretory.deadGodNameA','feretory.deadGodNameB','feretory.deadGodNameC'],'Dead god name: three independent d10 columns',62)]:
    add('feretory',slug(title),p,'Supplement class names',title,'Procedure','RESOLVED','The printed multi-column name process is retained in class generation and the canonical component tables; it does not sum three dice into one index.',path='Characters → class generation; Reference → component tables',tableids=ids,code=['src/generators/characterClasses.ts:255'],frequency=2,friction=1,workflows=['Character'],context='yes')
names=['Dream Theory','Total Matter Comprehension','Ping the Shared Subconscious','Logical Prognostication','Carno-Organic Speleophagy','Time-Locked Pneumotoxin','Induced Irrelevance','Structural Cryo-condensation (Freezing Moon)','Meta-Alchemy','Memetic Cognitive Palpitation']
for i,name in enumerate(names):
    add('feretory','ochre-'+str(i+1),66,'The Tablets of Ochre Obscurity',name,'Power','PRESENT_BUT_INDIRECT','Full individual effect exists in reference-only canonical table, including numerical effects and exceptions; no direct named Power result exists in search.', 'Index each canonical named tablet entry; retain manual selection because this page supplies no general die expression.',path=f'oracle:feretory.ochreTablets → TABLE → {i+1}',queries=[name,'Ochre Tablets'],tableids=['feretory.ochreTablets'],solutions=['POWER_REFERENCE','SEARCH_ALIAS'],frequency=3,friction=3,workflows=['Character','Equipment','Powers'],printed='Inside back cover; no printed page number visible')
add('feretory','ochre-usage',66,'The Tablets of Ochre Obscurity','Tablet price, carrying, breakage, use eligibility and casting','Rule','PARTIAL','General tablet rules are absent from the table reference. A generated Philosopher playerRules result includes size/breakage/scroll-use only; the price and Presence+3-or-Philosopher restriction reside in internal class rules, not a general usable reference.', 'Add one shared usage rule and link it from each tablet and Philosopher; do not replace the English effect with a summary.',path='oracle:feretory.ochreTablets / Character class rules (incomplete)',queries=['Ochre Tablets','tablet casting'],tableids=['feretory.ochreTablets'],code=['src/generators/characterClasses.ts:360','src/domain/references.ts:405'],solutions=['QUICK_RULE','POWER_REFERENCE','RESULT_LINK'],frequency=4,friction=4,workflows=['Character','Powers','Equipment'],printed='Inside back cover; no printed page number visible')
for tid in ['feretory.blackSaltWindIntensity','feretory.saltSuffering']:
    table('feretory',tid,'The Black Salt',workflows=['Travel','Dungeon'])
add('feretory','black-salt-chain',68,'The Black Salt','Wind → Toughness → failed-test suffering','Procedure','PRESENT_BUT_INDIRECT','All wind DRs and suffering results, including result11 follow-up, are present. They are independent references without direct wind-to-consequence linkage; sourceNote supplies the trigger.', 'Add related canonical links in both directions and a small optional procedure reminder; keep the Toughness decision manual.',path='oracle:feretory.blackSaltWindIntensity → SOURCE; search Salt-Suffering',queries=['Black Salt','Salt-Suffering'],tableids=['feretory.blackSaltWindIntensity','feretory.saltSuffering'],solutions=['RESULT_LINK','CONTEXT_LINK'],frequency=2,friction=3,workflows=['Travel','Dungeon'],printed='Back cover')

# HERETIC tables, feats and scenario-local material.
for tid in ['heretic.cultName0','heretic.cultName1','heretic.cultKeyMember0','heretic.cultKeyMember1','heretic.cultKeyMember2','heretic.cultStatus','heretic.cultHeadquarters','heretic.cultDoctrine','heretic.cultHates']:
    table('heretic',tid,'Seeds of a Cvlt',workflows=['NPC','Dungeon'])
add('heretic','cult-column-procedure',[2,3],'Seeds of a Cvlt','Two-column name and three-column member procedure','Procedure','PRESENT_BUT_INDIRECT','All source columns are canonical tables but there is no grouped Seeds of a Cvlt reference procedure to preserve the printed independent-column selections in one inspection.', 'Add a compact grouped source reference linking the existing columns; no faction management feature is needed.',path='Reference → individual cult tables',tableids=['heretic.cultName0','heretic.cultName1','heretic.cultKeyMember0','heretic.cultKeyMember1','heretic.cultKeyMember2'],solutions=['PROCEDURE','CONTEXT_LINK'],frequency=2,friction=3,workflows=['NPC','Dungeon'],printed='First fold, unnumbered')
table('heretic','heretic.unheroicFeats','Unheroic Feats',workflows=['Character','Combat'])
add('heretic','feat-eligibility',6,'Unheroic Feats','Optional advancement and feat acquisition','Rule','RESOLVED','Classless eligibility, maximum three and GM choice/random/narrative options are present as a concise rule linked to the complete feat table.',path='rule:heretic.feat-eligibility',tableids=['heretic.unheroicFeats'],code=['src/domain/playReferenceRules.ts:273'],frequency=3,friction=1,workflows=['Character'],context='yes')
add('heretic','feat-named-lookup',range(6,12),'Unheroic Feats','Retrieve a particular feat by its printed name','Aid','PRESENT_BUT_INDIRECT','All36 feat effects are complete table rows, but exact feat names such as Party Chef/Outback Survivalist are not indexed; user must know Unheroic Feats and scan the table.', 'Add aliases opening/highlighting existing feat rows; no automatic advancement system required.',path='oracle:heretic.unheroicFeats → TABLE',queries=['Party Chef','Outback Survivalist','Bloodied Knuckles'],tableids=['heretic.unheroicFeats'],solutions=['SEARCH_ALIAS','RESULT_LINK'],frequency=3,friction=3,workflows=['Character','Travel','Combat'])
for tid in ['heretic.songbird.deal','heretic.songbird.instruments','heretic.songbird.spinalHusk','heretic.vicar.firstPeel.who','heretic.vicar.firstPeel.what','heretic.vicar.blessings','heretic.vicar.bloodEagle']:
    table('heretic',tid,'Supplement class tables',workflows=['Character'],context='yes')
for tid in ['heretic.gravesRandomEncounter','heretic.gravesSensoryStrangeness','heretic.gravesTrails','heretic.gravesLootBodies','heretic.gravesUrn','heretic.gravesUnkeyStrongbox']:
    table('heretic',tid,'Graves Left Wanting')
table('heretic','heretic.gravesKnowledge','Graves Left Wanting',state='PARTIAL',problem='Every claim has source truth/false/maybe metadata, but Reference reading/table view show only entry.text. The GM cannot distinguish the printed reliability without another source view/PDF.',fix='Display the existing reliability metadata in an intentional rule/table result detail; keep original claims unchanged.',solutions=['TABLE_VIEW','QUICK_RULE'])
add('heretic','graves-travel',22,'Graves Left Wanting','15-minute travel, encounter and fourth-location exit rule','Procedure','PARTIAL','Trail and encounter tables exist, but their source-defined sequencing and all-four-locations → Undertaker’s Hut rule are missing. Generic dungeon crawl does not implement this scenario procedure.', 'Add a static concise procedure card with links to trails/encounters and the exit condition; no scenario state machine needed.',path='oracle:heretic.gravesTrails / oracle:heretic.gravesRandomEncounter',tableids=['heretic.gravesTrails','heretic.gravesRandomEncounter','heretic.gravesSensoryStrangeness'],solutions=['PROCEDURE','RESULT_LINK'],frequency=3,friction=4)
add('heretic','graves-encounter-actors',22,'Graves Left Wanting','Encounter result → named creature stat block','Procedure','PRESENT_BUT_INDIRECT','Five printed encounter creatures have valid reference records, but the oracle result stores monster/quantity metadata without clickable creature routing. The user must search the name again.', 'Link named canonical creature references from the existing encounter metadata.',path='oracle:heretic.gravesRandomEncounter → second search for monster',tableids=['heretic.gravesRandomEncounter'],solutions=['RESULT_LINK'],frequency=3,friction=3,workflows=['Dungeon','Monster'])
# All17 HER creature definitions, distinguishing unusable no-HP record.
for c in pack['library']['creatures']:
    if c.get('book')!='heretic': continue
    name=c['name']; ref=next((r['id'] for r in index if r['kind']=='creature' and r['title'].split(' · ')[0]==name and ':heretic:' in r['id']), '')
    state='RESOLVED' if ref else 'PARTIAL'
    problem='Printed stat values, attacks and operational special rules are present and readable in the direct creature result.' if ref else 'Full source Mental Torture Prison mechanics are stored, but hp:null is filtered from Reference and Monster presets. The source intentionally has no conventional HP; treating it as unusable loses a complete encounter.'
    if name=='Borg Bitor':problem+=' Additional PDF63 Devil’s Glue detection/escape/countdown penalties are retained; trade valuations are audited separately.'
    if name=='The Übertaker':problem+=' Its d4 action table and loot-scroll effect are rendered with the definition.'
    pages=[c['pdfPage']]+([c['additionalSource']['pdfPage']] if c.get('additionalSource') else [])
    need={'Half-Billed Raven':'creature:half-billed-raven','Unbred Mutt':'creature:unbred-mutt','Twice-Grown Corpse Fly':'creature:twice-grown-corpse-fly'}.get(name)
    add('heretic','creature-'+slug(name),pages,c.get('context') or name,name,'Creature',state,problem,'None.' if ref else 'Make verified non-numeric-stat source creatures inspectable without manufacturing HP/armor; render its existing specialAbility.',path='Reference Desk → '+ref if ref else 'library.creatures → record stored but not exposed',queries=[name],code=['src/domain/references.ts:91','src/domain/references.ts:557','src/generators/monster.ts:362','src/domain/referenceExecution.ts:61'],solutions=[] if ref else ['MONSTER_REFERENCE'],frequency=3,friction=1 if ref else 5,workflows=['Monster','Dungeon'],printed=str(c.get('source',{}).get('printedPage') or 'Last fold, unnumbered'),need=need)
for c in pack['library']['outcasts']:
    if c.get('book')!='heretic':continue
    add('heretic','outcast-'+slug(c['name']),c['pdfPage'],c.get('context') or 'The Merchant',c['name'],'Creature','PARTIAL','The supplied data includes a complete named outcast stat block, special/behavior and possessions where printed. Reference registry and preset list read creatures only; no usable outcast lookup exposes this record.', 'Index existing outcasts as source NPC/creature references and include possession metadata, retaining their specific identity.',path='library.outcasts → stored data only',queries=[c['name']],solutions=['MONSTER_REFERENCE','SEARCH_ALIAS'],code=['src/domain/references.ts:557','src/components/Monsters.tsx:86','src/storage/rulesStore.ts:31'],frequency=3 if c['name']=='Mikhael' else 2,friction=5,workflows=['NPC','Dungeon','City'])
for key,pp,title,problem in [
 ('erhard-opening',24,'Opening Erhard’s sarcophagus','Strength threshold, assistant adjustment and damage on failure are absent.'),
 ('maus-acid',26,'Maus’ acid pools','Per-round flesh damage and the bone exception are absent.'),
 ('origin-fountain-hazard',27,'Origin Fountain crossing and aging','Separate access tests and permanent ability-loss consequence are absent.'),
 ('sewer-currents',30,'Shadow King’s Sewer currents','Contact test, sweep-away and drowning danger are absent.')]:
    add('heretic',key,pp,'Graves Left Wanting',title,'Rule','MISSING',problem,'Add one short scenario-bound hazard reference; leave keyed prose/map in the PDF.',solutions=['QUICK_RULE'],frequency=2,friction=4)
for key,pp,title in [('skeleton-unkey',25,'The Skeleton Unkey'),('roseate-baritona',26,'The Roseate Baritona / Corrupted Horn of Roses'),('nostalgia-gruel',27,'Nostalgia Gruel')]:
    add('heretic',key,pp,'Graves Left Wanting',title,'Item','MISSING','Source gives a named usable effect; current tables include neighboring random results but not this item rule.', 'Add a named item reference with the printed effect, access restrictions and source link.',solutions=['ITEM_REFERENCE'],frequency=2,friction=5,workflows=['Equipment','Dungeon'])
add('heretic','behold-power-scroll',33,'Graves Left Wanting','Behold the Power — torn Übertaker robes','Power','PRESENT_BUT_INDIRECT','Complete spell effect is rendered as Übertaker loot, but its Power name resolves primarily to the boss action/table instead of a loot-scroll reference.', 'Link the existing loot text as its own Power alias, preserving distinction from the boss’s next-attack action.',path='The Übertaker → Loot',queries=['Behold the Power'],solutions=['POWER_REFERENCE','RESULT_LINK'],frequency=2,friction=3,workflows=['Powers','Dungeon'])
add('heretic','animated-waste',35,'A Gluttonous Dungeon / Bloat','Animated waste','Creature','MISSING','Source defines a no-HP creature with acid attack, cannot-be-killed/dissipation rule and ambient penalty. No record exists; a numeric-HP requirement must not exclude it.', 'Add a source creature with absent HP and its literal dissipation/effect rules.',solutions=['MONSTER_REFERENCE'],frequency=2,friction=5,workflows=['Dungeon','Monster'])
for key,pp,title,typ,problem in [
 ('gourmands-cutlery',34,'The Gourmand’s Cutlery','Item','Eat-anything, compulsory hunger and automaton command function are missing from item lookup; Silas stats alone do not cover it.'),
 ('tongue-knife',35,'Tongue-shaped knife','Item','The damage and mandatory eat/drink-within-hour consequence are missing.'),
 ('bloat-tripwire',[34,35],'Moldy-curtain tripwire','Rule','Describe-search/Presence detection and falling-block damage are missing.'),
 ('bloat-statue',35,'Chapel of Filth statue compulsion','Rule','The Presence test and offering-self-for-dinner consequence are absent.')]:
    add('heretic',key,pp,'A Gluttonous Dungeon / Bloat',title,typ,'MISSING',problem,'Add the compact scenario-specific effect with original source provenance.',solutions=['ITEM_REFERENCE'] if typ=='Item' else ['QUICK_RULE'],frequency=2,friction=4)
for tid in ['heretic.curses','heretic.curseHelper','heretic.curseKnowledgePrice']:
    table('heretic',tid,'You Are Cursed',workflows=['Solo','Character'])
table('heretic','heretic.curseCure','You Are Cursed',state='SOURCE_UNAVAILABLE',problem='Result12 ends mid-sentence at the physical lower page edge of the supplied PDF. The application retains the visible fragment and source warning. This is an incomplete supplied source, not an invented fallback or a missing import.',fix='Obtain a complete authorized copy of this one source row, or retain its explicit unavailable suffix; do not guess the ending.',solutions=['SOURCE_MISSING'],workflows=['Solo','Character'],notes='Fresh HER PDF37 rendered and inspected at lower right: result12 literally ends after “do not”.')
table('heretic','heretic.merchant.soulPrice','The Merchant',workflows=['City','Equipment'])
add('heretic','merchant-trade',40,'The Merchant','Buying/selling for soul and daily regional stock','Procedure','PRESENT_BUT_INDIRECT','Regional stock, buy-cost table and reversed sell gain are all available across source notes; there is no compact Mikhael trade reference or links among the four stock tables and price rule. Mikhael actor itself is separately unexposed.', 'Group existing stock/price references and expose the buy-versus-sell distinction, including the wagon/basic equipment note.',path='oracle:heretic.merchant.soulPrice → SOURCE; regional stock tables',queries=['Mikhael','Merchant','soul price'],tableids=['heretic.merchant.soulPrice'],solutions=['PROCEDURE','CONTEXT_LINK','RESULT_LINK'],frequency=3,friction=3,workflows=['City','Equipment'])
merchant_names={
 'tveland':['Stone Dagger','Tongue of a False Prophet','Two-headed Silver Ring','Vial of Goblin Ichor','Wickhead Brain','Galgenbeck Deathmask'],
 'wastland':['Pouch of Valley Vapors','Jar of Troll Piss','Fine but Gaudy Clothing','Pilgrim’s Compass','Peasant’s Kuksa','Lucky Fishing Spear'],
 'kergus':['Vibrant Red Ribbon','Vial of Glowing Blue Blood','Gleaming Golden Scalpel','Pleasing Green Cloak','One-eyed, One-legged, One-winged Gull','Bright Yellow Flower'],
 'grift':['Little Poppet','Key Retrieved from the Múr','Chip the Rat','Sorrowful Music Box','Hangman’s Rope','Giant’s Chisel']}
for (region,names),page in zip(merchant_names.items(),[42,43,44,45]):
    tid='heretic.merchant.stock.'+region
    for i,name in enumerate(names):
        add('heretic','merchant-'+region+'-'+str(i+1),page,'The Merchant / '+region,name,'Creature' if name=='Chip the Rat' else 'Item','PRESENT_BUT_INDIRECT','The full source effect (including Chip’s actual stats where applicable) is in the canonical stock row. Exact item names are not indexed; retrieving a specific purchase requires knowing the region/stock table.', 'Index a named alias opening the existing row, with a soul-price link. Do not duplicate the source payload.',path=f'oracle:{tid} → TABLE → {i+1}',queries=[name,'Merchant '+region],tableids=[tid],solutions=['ITEM_REFERENCE','SEARCH_ALIAS','RESULT_LINK'],frequency=3,friction=3,workflows=['Equipment','City'])
add('heretic','blackpowder-rule',46,'Blackpowder Weapons for the Rich and Foolhardy','Blackpowder attack, armor, reload and noise rules','Rule','MISSING','The complete general blackpowder rules are absent from quick references and source tables. An AITC firearms mention is not this rule: source defines Presence DR14, ignored armor, reload limitations/time and noise consequences.', 'Add a source-specific quick rule linked to a static weapon/ammunition list; no combat simulator needed.',severity='P1',frequency=4,friction=5,queries=['blackpowder','firearms','reload','BWFTRAF'],solutions=['QUICK_RULE','CONTEXT_LINK'],workflows=['Equipment','Combat'],printed='44',notes='Fresh PDF46 visually inspected. All weapon text is readable, no unavailable source.')
for name in ['Pistolet','Culverin','Arquebus','Dragon','Basilisk Gun','Blunderbuss','Heavy Arquebus','Pepperbox Pistolet','Blackpowder Bomb','Ribauldequin','Cannon']:
    add('heretic','blackpowder-'+slug(name),46,'Blackpowder Weapons for the Rich and Foolhardy',name,'Item','MISSING','Named weapon has printed damage/price and, where applicable, load, carry, multi-target or blast rules. No usable source item record exists. Generic Core equipment cannot substitute.', 'Add one named item reference from this page, linked to the shared blackpowder rule.',severity='P2',frequency=3,friction=5,solutions=['ITEM_REFERENCE','SEARCH_ALIAS'],workflows=['Equipment','Combat'],printed='44')
add('heretic','blackpowder-ammunition',46,'Blackpowder Weapons for the Rich and Foolhardy','Powdershot, basilisk-shot and cannon-shot prices','Table','MISSING','All three printed ammunition quantity/price rows are absent.', 'Include the three rows with the shared blackpowder equipment reference.',frequency=3,friction=4,solutions=['TABLE_INDEX','ITEM_REFERENCE'],workflows=['Equipment'],printed='44')
table('heretic','heretic.swampWitch.rumors','Sepulchre of the Swamp Witch')
for title,pages in [('Emerald Serpent',51),('Strange Serpent Drug Cultist',51),('Ueth the Scalehunter',52),('Forked-Tongue Devotee',54),('The Swamp Witch',57),('Srolki',58),('Yaoxl',58)]:
    add('heretic','swamp-'+slug(title),pages,'Sepulchre of the Swamp Witch',title,'Creature','MISSING','The source provides a distinct complete stat block with conditional attacks/venom/powers/resurrection as applicable. Existing wishes/rumor names are not creature definitions.', 'Add the printed creature definition and link relevant scenario table results; preserve any intentionally unprinted Morale.',solutions=['MONSTER_REFERENCE','RESULT_LINK'],frequency=2,friction=5,workflows=['Dungeon','Monster'])
for key,pp,title,typ,problem in [
 ('emerald-venom',[50,51],'Emerald Venom and invisible passage rules','Rule','Duration, initiative/fumble penalties and perception/door conditions are absent.'),
 ('slithering-strangulation',52,'Slithering Strangulation','Power','Named source scroll with count/duration/damage/retarget risk is entirely absent.'),
 ('croaking-trident',55,'The Croaking Trident','Item','Damage types and kill-count transformation thresholds are absent.'),
 ('lunar-zweihander',57,'Lunar Zweihänder','Item','Armor exception and radiance effect are absent; tied to source Swamp Witch weapon, not a generic two-handed sword.'),
 ('ranseur-maelstrom',58,'Ranseur of the Maelström','Item','Source weapon’s damage and life transfer are absent; Yaoxl name in wishes does not expose it.'),
 ('venomous-adders',55,'Venomous adders guarding the Hidden Ferns','Rule','Source describes an Agility hazard/conditional bite, not an independent HP statblock. The actual hazard is absent.'),
 ('ethereal-snakes',52,'Ethereal ceiling snakes','Rule','Two-attack damage-and-disappear response is absent; source supplies no full creature stats.'),
 ('klopstock-ring',54,'Klopstock ruby ring','Item','Source-specific ordinary sale value and named-heir return value are absent.')]:
    add('heretic','swamp-'+key,pp,'Sepulchre of the Swamp Witch',title,typ,'MISSING',problem,'Add the short literal source-specific reference; do not manufacture missing stats or generalize the scenario.',solutions=['POWER_REFERENCE'] if typ=='Power' else ['ITEM_REFERENCE'] if typ=='Item' else ['QUICK_RULE'],frequency=2,friction=5,workflows=['Dungeon','Equipment','Powers'])
table('heretic','heretic.swampWitch.wishes','Sepulchre of the Swamp Witch')
add('heretic','wish-procedure',59,'Sepulchre of the Swamp Witch','Dead Root Altar wishes, willing sacrifice and Doom exception','Procedure','PARTIAL','Six aftermath results and the unwilling-only trigger note are present. The fixed willing-sacrifice damage/tests/witch arrival and the precise delay-of-Doom rule are not in the application; table existence alone cannot run this procedure.', 'Add a short precondition/outcome rule linked to the existing d6 table, distinguishing the fixed willing branch from rollable aftermath.',path='oracle:heretic.swampWitch.wishes → SOURCE (trigger only)',tableids=['heretic.swampWitch.wishes'],solutions=['QUICK_RULE','PROCEDURE'],frequency=2,friction=5)
add('heretic','bowyers-bow',60,'The Bone Bowyer','The Bowyer’s Bow','Item','MISSING','Creature record preserves its own attack but not the usable bow’s miss-retarget loop or immunity exception. This is a separate source item, not merely the creature weapon’s damage.', 'Add the named item’s full concise rule and link it from the Bone Bowyer result.',solutions=['ITEM_REFERENCE','RESULT_LINK'],frequency=3,friction=5,workflows=['Equipment','Monster'])
add('heretic','bowyer-services',60,'The Bone Bowyer','Unsavory Services','Table','MISSING','Six source commission prompts for obtaining a bow are absent. The source supplies a request list, no die instruction.', 'Add a non-rollable source option list under the Bowyer service/item reference.',solutions=['TABLE_INDEX','RESULT_LINK'],frequency=2,friction=4,workflows=['NPC','Equipment'])
add('heretic','bitor-valuation',63,'Borg Bitor','Borg Bitor trade valuations and intact black egg','Table','PRESENT_BUT_INDIRECT','Alive/glue/mandible/egg values exist in record.valuation and generated Monster notes. Direct Reference result omits notes, so these useful values are not available from ordinary lookup.', 'Expose a quiet trade-values disclosure from existing valuation metadata.',path='Monsters → load Borg Bitor preset → notes; direct Reference omits valuations',queries=['Borg Bitor','Devil’s Glue','Intact black egg'],solutions=['ITEM_REFERENCE','RESULT_LINK'],frequency=2,friction=3,code=['src/generators/monster.ts:519','src/domain/referenceExecution.ts:61'],workflows=['Equipment','Monster'])
table('heretic','heretic.nurse.corridorNorth','Nurse the Rot')
for key,pp,title,problem in [
 ('nurse-alert',67,'Rotten Nurse alert and investigation procedure','Four alert triggers, destination d4+1 and ten-minute reroll are absent.'),
 ('nurse-corridor-east',67,'Corridor East well-spider hazard','The low Agility DR and instantly fatal caught consequence are absent; no separate monster HP is provided.'),
 ('nurse-poisoned-coins',67,'Poisoned corpse coins','Amount and one-in-twenty fatal contact risk are absent.'),
 ('nurse-nest-advancement',66,'Bitor Nest improvement and healing fungus','Source awards only ability/HP improvement on entry and a healing fungus amount; both quick rules are absent.')]:
    add('heretic',key,pp,'Nurse the Rot',title,'Rule','MISSING',problem,'Add a concise scenario-local rule; preserve map/discovery detail in PDF.',solutions=['QUICK_RULE'],frequency=2,friction=4,printed='Last fold, unnumbered')
add('heretic','nurse-bomb',67,'Nurse the Rot','Bomb in Dim Room','Item','MISSING','The source provides a compact bomb damage instruction. No source item reference exposes it.', 'Link to this local bomb text and distinguish its wording from the Blackpowder Bomb general entry.',solutions=['ITEM_REFERENCE'],frequency=2,friction=4,workflows=['Equipment','Dungeon'],printed='Last fold, unnumbered')
add('heretic','staff-awful-light',66,'Nurse the Rot','Staff of Awful Light','Source reference','SOURCE_UNAVAILABLE','The supplied adventure names the staff as the objective and locates it, but provides no effect or stat rule. No application omission can be inferred for mechanics the PDF never states.', 'Preserve the named objective/source link if desired; do not invent a Power or item effect.',severity='P3',frequency=1,friction=2,solutions=['SOURCE_MISSING'],printed='Last fold, unnumbered')

# PDF-suitable content is accounted for explicitly, separate from quick mechanics.
for b,key,pages,title in [
 ('feretory','front-art',[1,4,5,10,11,13],'Covers, credits and chapter-opening artwork'),
 ('feretory','ziggurat-long',range(24,34),'The Death Ziggurat map, premise and keyed location prose'),
 ('feretory','grinder-long',range(35,49),'The Goblin Grinder premise, maps and keyed location prose'),
 ('feretory','reliquary-art',49,'Tenebrous Reliquary opening art and credits'),
 ('feretory','class-art',[59,61,63,67],'Class illustrations and blank/low-text art folds'),
 ('heretic','front-art',[1,4,5,13,15,16,17],'Cover, credits and class/chapter artwork'),
 ('heretic','graves-long',range(18,34),'Graves Left Wanting premise, keyed map and long-form location text'),
 ('heretic','bloat-long',[34,35],'Bloat map and long-form adventure structure'),
 ('heretic','merchant-long',[38,39,40,41],'Mikhael background and chapter artwork'),
 ('heretic','swamp-long',range(47,60),'Swamp Witch map, premise, hidden routes and keyed prose'),
 ('heretic','late-art',[61,63,64,65,66,67,68],'Creature background, Bitor’s Spawn lore, Nurse the Rot map, art and back-cover poem')]:
    add(b,key,pages,'Visual / long-form source',title,'Long-form','PDF_APPROPRIATE','Keeping scenario geography, scene-setting and artwork in the supplied PDF is appropriate. Quick stat blocks, named item effects and mechanical triggers on the same pages are audited as separate actionable rows.',code=[],workflows=['Dungeon'])
for b,pages,title,problem in [
 ('dark-fort',[1,2,3],'DARK FORT independent solo microgame','The PDF explicitly identifies a separate predecessor microgame. Its d6-vs-monster-points combat, fixed Kargunt character, own inventory/level rules, room tables and monsters are not ordinary MÖRK BORG missing rules. Keep as a separately identified standalone game PDF; do not mix its statlines into MB generators.'),
 ('dark-fort-sheet',[1],'DARK FORT Kargunt worksheet','Auxiliary printable character/map sheet for the independent DARK FORT microgame, not an MB class or campaign schema requirement.'),
 ('feretory-sv',range(1,11),'Swedish FERETORY alternate-language source','Cover plus Swedish Monster Approaches, traits, Grey Galth Inn, Three Dead Skulls, Philosopher, Ochre Tablets, Black Salt and art. These overlap FER English sections with edition/translation differences; not a second set of missing MB rules. Do not silently replace English canonical fragments with Swedish wording.'),
 ('death-ziggurat-map',[1],'Death Ziggurat player-facing hex map','Auxiliary player handout with one-hex/15-minute scale. It is not an additional oracle or independent adventure. The scale/exploration need is counted under FER PDF27–29.')]:
    add(b,'source-aid',pages,'Independent / auxiliary / duplicate source',title,'Aid','PDF_APPROPRIATE',problem,code=[],workflows=['Solo'] if b.startswith('dark-fort') else ['Dungeon'],printed='Unnumbered / source-specific')

# Individual physical-page ledger; mixed pages explicitly retain both dispositions.
FER_SECTIONS={1:'Cover',2:'Monster Approaches A/B/C and stat derivation',3:'Monster desire / traits',4:'Contents / credits',5:'Roads title',6:'Travel distances map and scaling',7:'Travel checklist / roads / events',8:'Forage / village',9:'Off-road encounters / camp events',10:'EPK opening art',11:'EPK title / credits',12:'Hunting rules / mishaps / belly',13:'EPK title art',14:'Tveland EPK',15:'Sarkash EPK',16:'Graven-Tosk EPK',17:'Grift EPK',18:'Kergüs EPK',19:'Wästland EPK',20:'Lake Onda EPK',21:'Valley EPK',22:'Bergen EPK first half',23:'Bergen EPK second half',24:'Death Ziggurat title',25:'Death Ziggurat title / credits',26:'Ziggurat premise and surrounding cultists',27:'Ziggurat referee hex map / fifteen-minute scale',28:'Depression / flowers / channeling',29:'Ruins exploration tables',30:'Spiral Chapel / Crown / heart / Ziggurat',31:'Ziggurat artwork',32:'Ziggurat four monster/NPC definitions',33:'Cultist / Akünh definitions',34:'d100 items and trinkets',35:'Goblin Grinder title',36:'Goblin Grinder premise',37:'Goblin Grinder artwork',38:'Hooks / Calumny Pearl / scheme / curse',39:'Qarg / Nagel / Bastard',40:'Goblin Grinder artwork',41:'Medickal Shoppe consumables / prices',42:'Mill lower map / escalation',43:'Mill upper map',44:'Barricade / liquid / fuse warning',45:'Cannon / basement / excited goblins / remedy',46:'Oil / archer and bucket goblins',47:'Alchemy trigger / effects / Ooze',48:'Grinder operation / final encounter stat blocks',49:'Reliquary opening / d66 title',50:'Reliquary 11–16',51:'Reliquary 21–26',52:'Reliquary 31–36',53:'Reliquary 41–46',54:'Reliquary 51–56',55:'Reliquary 61–66',56:'Inn menus / prices / keeper / patrons',57:'Three Dead Skulls / payouts / Dreg / Rat / names',58:'Cursed Skinwalker',59:'Skinwalker illustration',60:'Pale One',61:'Pale One illustration',62:'Dead God’s Prophet',63:'Prophet illustration',64:'Forlorn Philosopher',65:'Philosopher roots',66:'Ochre Tablets effects and usage',67:'Fold artwork',68:'Black Salt wind and suffering'}
HER_SECTIONS={1:'Cover',2:'Cult seed columns / status / headquarters',3:'Cult doctrine / hatred',4:'Contents / credits',5:'Feats chapter opening',6:'Feat acquisition and 11–13',7:'Feats14–22',8:'Feats23–32',9:'Feats33–44',10:'Feats45–54',11:'Feats55–66',12:'Sacrilegious Songbird',13:'Songbird art',14:'Shedding Vicar',15:'Vicar art',16:'Graves opening artwork',17:'Graves title / credits',18:'Graves introduction / starting situation',19:'Graves illustration',20:'Graves map left',21:'Graves map right / d4 travel',22:'Travel procedure and four tables',23:'Five Graves monster definitions',24:'Plague Pit loot / Erhard hazard',25:'Fogbound Skeleton / Unkey / strongbox',26:'Maus acid / Roseate Baritona',27:'Urns / Corpse Fly / fountain / gruel',28:'Graves art',29:'Roach Herder NPC',30:'Sewer currents',31:'Strangly Tree location',32:'Deadn’t NPCs and hut',33:'Übertaker actions / loot Power',34:'Bloat map / automatons / ratbadger / cutlery',35:'Bloat Silas / animated waste / tongue-knife / hazards',36:'Curses d20',37:'Helpers / price / clipped cure12',38:'Merchant opening',39:'Merchant credits',40:'Mikhael / soul-price trading',41:'Merchant art',42:'Tveland stock',43:'Wästland stock',44:'Kergüs stock',45:'Grift stock / Chip',46:'Blackpowder rules / weapons / ammo',47:'Swamp Witch title',48:'Swamp Witch intro / rumors',49:'Swamp Witch art',50:'Swamp map / unseen passages',51:'Emerald Serpent / cultist / venom',52:'Ueth / Slithering Strangulation / EV hazards',53:'Swamp Witch art',54:'Devotee / snake pit / ring',55:'Trident / adders / garden',56:'Swamp Witch art',57:'Swamp Witch boss / Lunar sword',58:'Srolki / Yaoxl / ranseur / altar location',59:'Wish procedure / aftermath / willing branch',60:'Bone Bowyer / services / bow',61:'Bowyer art',62:'Borg Bitor stats',63:'Bitor spawn lore / glue / valuations',64:'Rotten Nurse mechanics / lore',65:'Nurse artwork',66:'Nurse map / Hag / Sludger / nest / corridor table',67:'Nurse map / Kôbôlth / traps / triggers / bomb',68:'Back-cover poem / art'}
ledger=[]
for book in BOOKS:
    source=json.loads((ROOT/f'outputs/pdf-escape-audit/extracted/{book}.json').read_text())
    for p in source['pageText']:
        n=p['pdfPage']; matched=[r for r in rows if r['bookId']==book and n in r['pdfPage']]
        assert matched,(book,n)
        title=(FER_SECTIONS if book=='feretory' else HER_SECTIONS if book=='heretic' else {}).get(n,'Independent / auxiliary source page')
        printed='First fold / unnumbered' if n in [2,3] else str(n-2) if 5<=n<=65 else 'Unnumbered / cover / fold'
        if book=='feretory' and n==66:printed='Inside back cover; no printed number visible (extracted legacy header is not visible)'
        if book=='heretic' and n>=66:printed='Last fold / back cover, unnumbered'
        if book not in ['feretory','heretic']:printed='Source-specific / not ordinary MB pagination'
        ledger.append({'bookId':book,'pdfPage':n,'printedPage':printed,'section':title,'needIds':[r['needId'] for r in matched],'classifications':sorted(set(r['classification'] for r in matched)),'pdfAppropriateExclusion':any(r['classification']=='PDF_APPROPRIATE' for r in matched),'review':'Fresh full-page text read; dense page layouts additionally rendered where referenced in report.'})
assert len({r['id'] for r in rows})==len(rows)
assert all(t in tables for r in rows for t in r['evidence']['tableIds'])
OUT.mkdir(parents=True,exist_ok=True)
(OUT/'supplement-rows.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
(OUT/'supplement-page-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n')
summary={b:{s:sum(r['bookId']==b and r['classification']==s for r in rows) for s in ['RESOLVED','PRESENT_BUT_INDIRECT','PARTIAL','MISSING','PDF_APPROPRIATE','SOURCE_UNAVAILABLE']} for b in BOOKS}
print(json.dumps({'rows':len(rows),'pages':len(ledger),'byBook':summary},indent=2))
